### ISSUE TITLE
Symfony 5.2.* TreeBuilder issue

### ISSUE THREAD

**Issue by AnPlandolit** [gonzakpo/afip#1]
Hola! el TreeBuilder da un error. Creo que la solución es modificar vendor->gonzakpo->afip-bundle->src->DependencyInjection->configuration.php

`        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->Root('parameters');`

por

`        $treeBuilder = new TreeBuilder('afip');
        $rootNode = $treeBuilder->getRootNode('parameters');`

**Comment by gonzaloalonsod** [comment]
@AnPlandolit Hola, hice algunas modificaciones, ahora deberias utilizar:
composer require gonzaloalonsod/afip-bundle

Si lo puedes probar y soluciona este error me avisas.
Gracias!

**Comment by AnPlandolit** [comment]
> 
> 
> @AnPlandolit Hola, hice algunas modificaciones, ahora deberias utilizar:
> composer require gonzaloalonsod/afip-bundle
> 
> Si lo puedes probar y soluciona este error me avisas.
> Gracias!

Works like a charm!

**Comment by gonzaloalonsod** [comment]
> > @AnPlandolit Hola, hice algunas modificaciones, ahora deberias utilizar:
> > composer require gonzaloalonsod/afip-bundle
> > Si lo puedes probar y soluciona este error me avisas.
> > Gracias!
> 
> Works like a charm!

Si te interesa aportar al bundle, bienvenido!
